language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - public
    - .cache
script:
  - cd front
  - yarn build 

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: front/build
  github-token: $GITHUB_TOKEN
  keep-history: true
  # Git branch on which it should deploy (master, gh-pages, foo...)
  target_branch: gh-pages
  on:
    branch: master

