version: "3.9"

services:
    frontend:
        build:
            context: ./front
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./front:/code
            - /code/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_API_URL=http://localhost:9000
        ports:
            - 3000:3000
        links:
            - api
        networks:
            - todoappnetwork
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        # restart: always
        ports:
            - 9000:9000
        volumes:
            - ./api:/api
            - ./api/nodemon.json:/api/nodemon.json
            - /api/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
            - NODE_ENV=production
            - CONNECTION_STRING=mongodb://db:27017/todo
        depends_on:
            - db
        networks:
            - todoappnetwork

    db:
        image: mongo:4.2
        restart: unless-stopped
        container_name: db
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017
        networks:
            - todoappnetwork
        logging:
            driver: none

networks:
    todoappnetwork:
        driver: bridge

volumes:
    mongodata: