version: "3.9"

services:
    frontend:
        build:
            context: ./front
            dockerfile: Dockerfile
        # restart: always
        volumes:
            - ./front:/code
            - /code/node_modules
            - ${HOME}/.ssh:/root/.ssh:ro
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - 3000:3000
        links:
            - api
        networks:
            - todoappnetwork
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        # restart: always
        ports:
            - 9000:9000
        volumes:
            - ./api:/api
            - ./api/nodemon.json:/api/nodemon.json
            - /api/node_modules
            - ${HOME}/.ssh:/root/.ssh:ro
        networks:
            - todoappnetwork

networks:
    todoappnetwork:
        driver: bridge
