version: "3.9"

services:
    web:
        build:
            context: ./front
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./front:/code
            - /code/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_API_URL=http://localhost:9000
        ports:
            - 3000:3000
        links:
            - api
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        ports:
            - 9000:9000
        volumes:
            - ./api:/api
            - ./api/nodemon.json:/api/nodemon.json
            - /api/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
            - CONNECTION_STRING=mongodb://db:27017/todo
            - PORT=9000
        depends_on:
            - db

    db:
        image: mongo:4.2
        restart: unless-stopped
        container_name: db
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017
        logging:
            driver: none

volumes:
    mongodata: