version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - /code/node_modules
      - ${HOME}/.ssh:/root/.ssh:ro
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
